version: '3'

services:
    govibrowser:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: govibrowser
        ports:
            - 8080:80
        volumes:
            - ./../:/var/www/html/